## Common Developer Tools

 choco install -y 7zip  
#choco install -y avidemux
 choco install -y azure-data-studio
 choco install -y baretail
 choco install -y firefox 
 choco install -y git 
 choco install -y googlechrome 
 choco install -y grepwin 
#choco install -y inkscape
 choco install -y insomnia-rest-api-client
 choco install -y notepadplusplus 
#choco install -y paint.net 
 choco install -y poshgit 
#choco install -y sql-server-management-studio
 choco install -y tortoisegit 
#choco install -y winscp
 choco install -y vscode
